### ISSUE TITLE
Upgrade"circleci/" containers

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#2956]
CircleCI writes: 

> Upgrade your pre-built container images by Dec. 31, 2021
> Legacy convenience images with the prefix “circleci/” will be deprecated on Dec. 31, 2021. If you haven't already, upgrade your projects with our latest [pre-built container images](https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/?mkt_tok=NDg1LVpNSC02MjYAAAGBCvy9jgxokd-bPMC4SbQwP_ChP3RttdcGhFiQ-smGNT5kfdS9uViwOlT9XCj6-3LLRbf6u3Er4gE__lrVwepHxGQ2UtZeiLCalfenl5obyy8) to optimize build times. All projects using legacy images have been notified via email - please see [Discuss](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034/3?mkt_tok=NDg1LVpNSC02MjYAAAGBCvy9jqbsScxR7H5IALfhiKk9TtOFYdjMjaBwWP3RZVv5LB7tC4cdXgvuDfhwnR5gUWNRrBfHQu5Z8FM1BIla8Fb78GzUAP7Psje5W692aJQ) for additional information and tips on moving to new images.

It seems that the solution suggested by CircleCI (using orbs to install the browser in the Python container) assumes one is running the tests in a docker executor, while we are using the machine executor for running the application tests.

Easiest solution seems to be to add a Dockerfile to `tests/application_tests` that has Python as base image and adds chrome and chromedriver plus selenium. And then use that container to run the tests (fragment from .circleci/config.yml):

```yaml
application_tests:
    machine: true
    parallelism: 1
    steps:
      - checkout
      - run: |
          export ENV=ci
          export COMPOSE_PATH_SEPARATOR=':'
          export COMPOSE_FILE=docker/docker-compose.yml:docker/docker-compose.ci.yml
          docker-compose build && docker-compose up -d
          docker build -f tests/application_tests/Dockerfile  -t ictu/quality_time_application_tests:v1.0
          docker run -it -w `pwd` -v `pwd`:`pwd` --network=container:qualitytime_www_1 ictu/quality_time_application_tests:v1.0 tests/application_tests/ci/test.sh
```
